image: Visual Studio 2015
environment:
  PATH: '%PATH%;C:\texlive\2017\bin\win32'
cache:
  - 'C:\texlive\2017\texmf-var\fonts\cache'
  - 'C:\texlive\2017\texmf-var\luatex-cache'
artifacts:
  - path: .\articles\hinagata\main_odd-ptex.pdf
    name: pTeX-odd
  - path: .\articles\hinagata\main_even-ptex.pdf
    name: pTeX-even
  - path: .\articles\hinagata\main_odd-luatex.pdf
    name: LuaTe-odd
  - path: .\articles\hinagata\main_even-luatex.pdf
    name: LuaTeX-even
  - path: .\articles\back_cover\back_cover.pdf
    name: BackCover
install:
  - git submodule update --init
  - choco install make
  - curl -O https://raw.githubusercontent.com/y-yu/install-tex-appveyor/master/install-tex.sh
  - bash ./install-tex.sh
  - tlmgr install latexmk collection-luatex collection-langjapanese collection-fontsrecommended type1cm mdframed needspace newtx fontaxes boondox everyhook svn-prov framed
build_script:
  - cd articles/hinagata
  - make
  - copy .\main_odd.pdf .\main_odd-ptex.pdf
  - copy .\main_even.pdf .\main_even-ptex.pdf
  - make clean
  - set LATEXMKFLAG=-lualatex
  - make
  - copy .\main_odd.pdf .\main_odd-luatex.pdf
  - copy .\main_even.pdf .\main_even-luatex.pdf
  - cd ../back_cover
  - make
  - copy .\main.pdf .\back_cover.pdf
