image: Visual Studio 2015
environment:
  PATH: '%PATH%;C:\texlive\2016\bin\win32;C:\Program Files\CMake\bin'
cache:
  - 'C:\texlive\2016\texmf-var\fonts\cache'
  - 'C:\texlive\2016\texmf-var\luatex-cache'
artifacts:
  - path: .\articles\hinagata\main-ptex.pdf
    name: pTeX
  - path: .\articles\hinagata\main-lua.pdf
    name: LuaTeX
install:
  - git submodule update --init
  - choco install cmake make
  - curl -O https://raw.githubusercontent.com/y-yu/install-tex-appveyor/master/install-tex.sh
  - bash ./install-tex.sh
  - tlmgr install latexmk collection-luatex collection-langjapanese collection-fontsrecommended filehook type1cm mdframed needspace unicode-math
build_script:
  - cd articles/hinagata
  - cmake -DENABLE_LUATEX=OFF .
  - cmake --build .
  - copy .\main.pdf .\main-ptex.pdf
  - cmake -DENABLE_LUATEX=ON .
  - cmake --build .
  - copy .\main.pdf .\main-lua.pdf
