image: Visual Studio 2015
environment:
  PATH: '%PATH%;C:\texlive\2017\bin\win32;C:\Program Files\CMake\bin'
cache:
  - 'C:\texlive\2017\texmf-var\fonts\cache'
  - 'C:\texlive\2017\texmf-var\luatex-cache'
artifacts:
  - path: .\articles\hinagata\main-ptex.pdf
    name: pTeX
  - path: .\articles\hinagata\main-lua.pdf
    name: LuaTeX
install:
  - git submodule update --init
  - choco install cmake
  - curl -O https://raw.githubusercontent.com/y-yu/install-tex-appveyor/master/install-tex.sh
  - bash ./install-tex.sh
  - tlmgr install latexmk collection-luatex collection-langjapanese collection-fontsrecommended type1cm mdframed needspace everyhook svn-prov
build_script:
  - cd articles/hinagata
  - cmake .
  - cmake --build .
  - copy .\main.pdf
