image: Visual Studio 2015
environment:
  PATH: '%PATH%;C:\texlive\2017\bin\win32'
cache:
  - 'C:\texlive\2017\texmf-var\fonts\cache'
  - 'C:\texlive\2017\texmf-var\luatex-cache'
artifacts:
  - path: .\articles\hinagata\main-ptex.pdf
    name: pTeX
  - path: .\articles\hinagata\main-luatex.pdf
    name: LuaTeX
  - path: .\articles\back_cover\back_cover.pdf
    name: BackCover
install:
  - git submodule update --init
  - choco install make
  - curl -O https://raw.githubusercontent.com/y-yu/install-tex-appveyor/master/install-tex.sh
  - bash ./install-tex.sh
  - tlmgr install latexmk collection-luatex collection-langjapanese collection-fontsrecommended type1cm mdframed needspace newtx fontaxes boondox everyhook svn-prov
build_script:
  - cd articles/hinagata
  - make
  - copy .\main.pdf .\main-ptex.pdf
  - make clean
  - set LATEXMKFLAG=-lualatex
  - make
  - copy .\main.pdf .\main-luatex.pdf
  - cd ../back_cover
  - make
