pipelines:
  branches:
    master:
      - step:
          name: Build the book
          image: wordcoins/latex-build:latest
          script:
            - git submodule update --init
            - WORD_FONT=sourcehan-jp make
          artifacts:
            - main.pdf
      - step:
          name: Upload the PDF
          deployment: production
          script:
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form "files=@main.pdf;filename=$BITBUCKET_BRANCH.pdf"
    articles/*:
      - step:
          name: Build a single article
          image: wordcoins/latex-build:latest
          script:
            - git submodule update --init
            - cd articles/`basename $BITBUCKET_BRANCH`
            - WORD_FONT=sourcehan-jp make
            - cp main.pdf ../../build.pdf
          artifacts:
            - build.pdf
      - step:
          name: Upload the PDF
          deployment: production
          script:
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form "files=@build.pdf;filename=`basename $BITBUCKET_BRANCH`.pdf"
  tags:
    '*':
      - step:
          name: Build the book
          image: wordcoins/latex-build:latest
          script:
            - git submodule update --init
            - WORD_FONT=sourcehan-jp make
          artifacts:
            - main.pdf
      - step:
          name: Upload the PDF
          deployment: production
          script:
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form "files=@main.pdf;filename=$BITBUCKET_TAG.pdf"
