pipelines:
  branches:
    master:
      - step:
          name: Build the book
          image: wordcoins/latex-build:latest
          max-time: 30
          caches:
            - fontcache
          script:
            - git submodule update --init
            - WORD_FONT=sourcehan-jp make
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form "files=@main.pdf;filename=$BITBUCKET_BRANCH.pdf"
          after-script:
            - ./scripts/notify_slack.sh
          artifacts:
            - main.pdf
    articles/*:
      - step:
          name: Build a single article
          image: wordcoins/latex-build:latest
          max-time: 10
          caches:
            - fontcache
          script:
            - git submodule update --init
            - cd articles/`basename $BITBUCKET_BRANCH`
            - WORD_FONT=sourcehan-jp make
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form "files=@main.pdf;filename=`basename $BITBUCKET_BRANCH`.pdf"
          after-script:
            - ./scripts/notify_slack.sh
          artifacts:
            - main.pdf
  tags:
    '*':
      - step:
          name: Build the book
          image: wordcoins/latex-build:latest
          max-time: 30
          caches:
            - fontcache
          script:
            - git submodule update --init
            - WORD_FONT=sourcehan-jp make
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form "files=@main.pdf;filename=$BITBUCKET_TAG.pdf"
          after-script:
            - ./scripts/notify_slack.sh
          artifacts:
            - main.pdf

  pull-requests:
    '**':
      - step:
          name: Build the book
          image: wordcoins/latex-build:latest
          max-time: 30
          caches:
            - fontcache
          script:
            - git submodule update --init
            - WORD_FONT=sourcehan-jp make
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form "files=@main.pdf;filename=$BITBUCKET_BRANCH.pdf"
          after-script:
            - ./scripts/notify_slack.sh
          artifacts:
            - main.pdf

definitions:
  caches:
    fontcache: /root/.texlive2018/texmf-var
