#!/usr/bin/env perl

$pdflatex = 'lualatex %O -synctex=1 -interaction=nonstopmode -shell-escape %B';
$latex= 'platex %O -synctex=1 -interaction=nonstopmode -kanji=utf8 -shell-escape %B';
$bibtex = 'pbibtex %O -kanji=utf8 %B';
# libpaperがJISに非対応のディストリビューションがあるため
$dvipdf= 'dvipdfmx %O -p jisb5 -d 5 -o %D %S || dvipdfmx %O -p b5 -d 5 -o %D %S';
$makeindex= 'mendex %O -U -r -c -g -s %B -p any %B';
$pdf_mode = 3;
$pdf_update_method = 3;
