name: CI

on: [push, pull_request]

jobs:
  build-article:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/word-coins/latex-build:latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_KEY }}
      AWS_EC2_METADATA_DISABLED: true
      PDF_BUILD_NOTIFY_URL: ${{ secrets.PDF_BUILD_NOTIFY_URL }}
      REPO_NAME: ${{ github.repository }}
      RUN_ID: ${{ github.run_id }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      # 事前にarticlesフォルダ内のmarkdownファイルに対してpandocを実行する
      - name: convert markdown to latex
        if: ${{ github.repository == 'WORD-COINS/article-template' }}
        run: |
          for filepath in $PWD/articles/*; do
            cd $filepath
            if [ -f ./main.md ]; then
              if [ ! -f ./main.tex ]; then
                echo $filepath
                make pandoc
              fi
            fi
          done

      - name: build article branch
        if: ${{ github.repository == 'WORD-COINS/article-template' }}
        run: |
          WORD_FONT=sourcehan-jp make

      - name: upload article template artifact
        if: ${{ github.repository == 'WORD-COINS/article-template' }}
        uses: actions/upload-artifact@v3
        with:
          name: article-template
          path: main.pdf

      - name: Notify Slack
        if: always()
        run: ./scripts/notify_slack.sh
        env:
          status: ${{ job.status }}
