name: CI

on:
  push:
    branches:
      - master
      - "articles/**"
  pull_request:
    branches:
      - master
      - "articles/**"

jobs:
  build-article:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/word-coins/latex-build:latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_KEY }}
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: extract branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: extract_branch

      - name: build master branch
        if: steps.extract_branch.outputs.branch == 'master'
        run: |
          WORD_FONT=sourcehan-jp make
          aws s3 --endpoint-url=https://minio.k8s.word-ac.net cp ./main.pdf s3://article-bucket/$REPO_NAME.pdf

      - name: build articles branch
        if: steps.extract_branch.outputs.branch == "articles/**"
        run: |
          ARTICLE_NAME=$(echo '${{ steps.extract_branch.outputs.branch }}' | awk -F '/' '{print $2}')
          cd ${{ steps.extract_branch.outputs.branch }}
          WORD_FONT=sourcehan-jp make
          aws s3 --endpoint-url=https://minio.k8s.word-ac.net cp ./main.pdf s3://article-bucket/$REPO_NAME-$ARTICLE_NAME.pdf
